name: deedee
description: DeeDee App
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.17.4 <3.0.0"

dependencies:
  shared_preferences: 2.0.15
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  firebase_auth_platform_interface: ^6.11.6
  cloud_firestore: ^4.3.0
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  # flutter_facebook_auth: ^5.0.6
  http: ^0.13.4
  image_picker: ^0.8.4+3
  firebase_storage: ^11.0.9
  cached_network_image: ^3.2.1
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  url_launcher: ^6.0.12
  fixnum: ^1.0.0
  async: ^2.2.0
  protobuf: ^2.0.0
  grpc: ^3.1.0
  location: 4.4.0
  geolocator: ^9.0.2
  flutter_map: ^3.1.0
  flutter_map_marker_cluster: ^1.0.1
  settings_ui: 2.0.2
  masked_text_field: 1.0.1
  event_bloc: ^4.2.0
  #  geocode: ^2.0.5
  get_it: ^7.1.4
  injectable:
  get: ^4.6.5
  uuid: ^3.0.6
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.0
  latlong2:
  search_address_repository:
    path: packages/search_address_repository
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  flutter_slidable: ^2.0.0

  sliding_up_panel: ^2.0.0+1
  dartx: ^1.1.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0

  cupertino_icons: ^1.0.3
  community_material_icon: ^5.9.55
  badges: ^3.0.2

  file_picker: ^5.2.5
  dio: ^5.0.0
  http_mock_adapter: ^0.4.2
  animated_button_bar: ^1.0.0
  flutter_native_splash: ^2.2.16


dev_dependencies:
  flutter_lints: ^2.0.1
  injectable_generator:
  build_runner:
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: "launcher_icon"
  image_path_android: assets/images/deedee_launcher_logo_android.png
  ios: true
  remove_alpha_ios: true
  image_path_ios: assets/images/deedee_logo.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf