name: deedee
description: DeeDee App
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.17.4 <3.0.0"

dependencies:
  shared_preferences: 2.0.15
  firebase_core: 1.24.0
  firebase_auth: 3.11.0
  firebase_auth_platform_interface: 6.10.0
  cloud_firestore: ^3.2.0
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  flutter_facebook_auth: ^3.5.3
  http: ^0.13.4
  image_picker: ^0.8.4+3
  firebase_storage: ^10.3.0
  cached_network_image: ^3.2.1
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  url_launcher: ^6.0.12
  fixnum: ^1.0.0
  async: ^2.2.0
  protobuf: ^2.0.0
  grpc: 3.0.2
  location: 4.4.0
  geolocator: ^9.0.2
  flutter_map: 3.0.0
  flutter_map_marker_cluster: 1.0.0
  settings_ui: 2.0.2
  masked_text_field: 1.0.1
  event_bloc: 4.1.0
  #  geocode: ^2.0.5
  get_it: ^7.1.4

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.17.0

  flutter_launcher_icons: ^0.10.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/deedee_logo.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/