// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiQd477ezdoQaJ-4HD0cbDIRZcH6p3BJo',
    appId: '1:710195196594:web:e0fc1d477b08a111da4fab',
    messagingSenderId: '710195196594',
    projectId: 'deedee-x',
    authDomain: 'deedee-x.firebaseapp.com',
    storageBucket: 'deedee-x.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsMdUfx6uqbvAwnrtQLi14JKo2WC1vhwo',
    appId: '1:710195196594:android:28379f51791a1f0bda4fab',
    messagingSenderId: '710195196594',
    projectId: 'deedee-x',
    storageBucket: 'deedee-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB58RlWBX47UKCl5VP3Yusy1CXMP7CRhyA',
    appId: '1:710195196594:ios:a73c6ca7a7023a32da4fab',
    messagingSenderId: '710195196594',
    projectId: 'deedee-x',
    storageBucket: 'deedee-x.appspot.com',
    iosClientId: '710195196594-7blf70eldt1vn8eqbjvt5ggmaserraa3.apps.googleusercontent.com',
    iosBundleId: 'io.instamobile.login.ios',
  );
}
