// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxJQcYNrcqs4Q-AEodtT6B0yuKBNtZGU4',
    appId: '1:32394661681:android:ebef3e49f38ad2adf5aa10',
    messagingSenderId: '32394661681',
    projectId: 'deedee',
    storageBucket: 'deedee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdKozXm8jwp_q2Edg_Ai9TY22bsLCe_bc',
    appId: '1:32394661681:ios:0157f36380f1b9baf5aa10',
    messagingSenderId: '32394661681',
    projectId: 'deedee',
    storageBucket: 'deedee.appspot.com',
    iosClientId: '32394661681-b5q19u1ujtsdnpb2s0h7fuhkb6edmgds.apps.googleusercontent.com',
    iosBundleId: 'io.instamobile.login.ios',
  );

  static const web = FirebaseOptions(
      apiKey: "AIzaSyDiQd477ezdoQaJ-4HD0cbDIRZcH6p3BJo",
      authDomain: "deedee-x.firebaseapp.com",
      projectId: "deedee-x",
      storageBucket: "deedee-x.appspot.com",
      messagingSenderId: "710195196594",
      appId: "1:710195196594:web:ef53b5cbd6e5038eda4fab"
  );
}
